### ISSUE TITLE
bad HTTP: 403

### ISSUE THREAD

**Issue by surfskidude** [kristapsdz/letskencrypt-portable#1]
I get the following error when I try to run the portable version:
letskencrypt: https://acme-v01.api.letsencrypt.org/acme/new-authz: bad HTTP: 403

I also had to disable IPv6 since letskencrypt initially tried to connect via an IPv6 address.

I also made some changes to the code since it would not compile on my Debian.

In extern.h, I changed
 include &lt;bsd/stdlib.h&gt;
 include &lt;/bsdstring.h&gt;
to
 include &lt;stdlib.h&gt;
 include &lt;string.h&gt;
BDW, the latter above is the correct way to include the standard header files.

I also changed main.c to use argv[0] instead of the BSD only 'getprogname()'.

**Comment by kristapsdz** [comment]
letskencrypt-portable needs libbsd for Linux systems.  It seems that this ran away from my README file--I'll re-add it, thanks!  However, I can't do much about your IPV6: it's being returned as a valid address, so you probably need to fix your system.  (I'm sure other systems will also pull down IPV6 addresses...)

As for the 403, the newest version will dump the output buffer from the server when it encounters are 403.  It usually means that you're using an unknown account key.
