### ISSUE TITLE
Use libwaive to implement functionality similar to pledge() in Linux

### ISSUE THREAD

**Issue by aperezdc** [kristapsdz/letskencrypt-portable#11]
In Linux, [libwaive](https://github.com/dimkr/libwaive) can be used to implement parts of the functionality of [pledge(2)](http://man.openbsd.org/pledge.2) without  having to deal with `seccomp` filters (or `libseccomp`) manually. I have an not-so-complete but functional [implementation of pledge(2) using libwaive](https://github.com/aperezdc/signify/blob/master/pledge_waive.c) which works fine for the [portable signify](https://github.com/aperezdc/signify) which I have been maintaining. You may want to pick the code from there — it uses the same BSD license as OpenBSD.

**Comment by kristapsdz** [comment]
libseccomp is actually pretty easy to use.  Am adding some bits now.  (Not enabled yet.)

**Comment by aperezdc** [comment]
@kristapsdz I am looking at the code you have been adding right now — you are right and it's not that difficult to use libseccomp directly. Maybe I'll add direct calls to it in Signify instead of going through libwaive :wink:

**Comment by kristapsdz** [comment]
I've now seccomp'd the whole shebang.  But since Linux is... a moving target... it might only work on my test system.  (Alpine.)  I'll try another VM with a glibc system to see if it works.  Meanwhile, if you try it and it bails on unauthorised system calls, it will report which system call failed.  These can usually be looked up in syscalls.h.

**Comment by aperezdc** [comment]
@kristapsdz: I have finally gotten round to try version 0.1.15, using Arch Linux (which is glibc-based) on a `x86_64` system, I get the following:

```
# acme-client -N -n -s perezdecastro.org
The seccomp sandbox has failed, error: 1:5.
Please report this number pair to the author.
The seccomp sandbox has failed, error: 3:5.
Please report this number pair to the author.
#
```

Assuming that the first number is the system call number, those correspond to:

```
% scmp_sys_resolver 1  
write
% scmp_sys_resolver 3
close
%
```

**Comment by kristapsdz** [comment]
Ok, now begins the cat-and-mouse of seccomp!  The first number is actually the process (you can look in extern.h, enum comp, and the index (0 = COMP_NET, etc.).  In this case, COMP_KEY and COMP_ACCOUNT  The second number is the system call.  In this case, that looks like fstat, which, because it's shared, probably should call in the sandbox_allow_stdio() set.

I've just checked in a patch.  This may take a little while: I've only tested on musl libc, and due to the nature of seccomp, every system call needs to be whitelisted.  Sigh!

**Comment by aperezdc** [comment]
@kristapsdz: Thanks! I'll try to build `master` later and see how that goes.

**Comment by cjsthompson** [comment]
I'm also using Arch Linux. I get this with the latest revision :

Dec 10 13:41:29 deposite systemd[1]: Starting Check and renew ACME TLS certificates...
Dec 10 13:41:29 deposite systemd[1]: Started Check and renew ACME TLS certificates.
Dec 10 13:41:29 deposite acme-client[26274]: acme-client: /var/lib/acme/accounts/letsencrypt.pem: account key exists (not creating)
Dec 10 13:41:29 deposite acme-client[26274]: The seccomp sandbox has failed, error: 4:95.
Dec 10 13:41:29 deposite acme-client[26274]: Please report this number pair to the author.
Dec 10 13:41:29 deposite acme-client[26274]: acme-client: /var/lib/acme/accounts/letsencrypt.pem: PEM_read_PrivateKey
Dec 10 13:41:29 deposite acme-client[26274]: 139802874757336:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem/pem_lib.c:704:Expecting: ANY PRIVATE KEY
Dec 10 13:41:31 deposite acme-client[26274]: acme-client: /var/lib/acme/certs/XXXXX/privkey.pem: generated RSA domain key
Dec 10 13:41:31 deposite acme-client[26274]: acme-client: bad exit: acctproc(26280): 1
Dec 10 13:41:31 deposite acme-client[26274]: acme-client: bad exit: challengeproc(26281): 1
Dec 10 13:41:31 deposite systemd[1]: acme@XXXXX.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 13:41:31 deposite systemd[1]: acme@XXXXX.service: Unit entered failed state.
Dec 10 13:41:31 deposite systemd[1]: acme@XXXXX.service: Failed with result 'exit-code'.

**Comment by repsac-by** [comment]
@cjsthompson You're using my package acme-client-git, he did not have permission to seccomp. I ~~~will soon do an update~~~ did update PKGBUILD.

**Comment by repsac-by** [comment]
@kristapsdz Consider my offer. May be better to make new breaking features was disabled by default and are switched through flags of compilation. If someone wants to use them he must do it consciously. Allow to use default in a new major version.

**Comment by cjsthompson** [comment]
Thanks, repsac-by. Rebuilding it and giving it a shot now:

Dec 11 11:32:34 deposite systemd[1]: Starting Check and renew ACME TLS certificates...
Dec 11 11:32:34 deposite systemd[1]: Started Check and renew ACME TLS certificates.
Dec 11 11:32:34 deposite acme-client[28424]: acme-client: /var/lib/acme/accounts/letsencrypt.pem: account key exists (not creating)
Dec 11 11:32:34 deposite acme-client[28424]: acme-client: /var/lib/acme/certs/XXXXX/privkey.pem: domain key exists (not creating)
Dec 11 11:32:34 deposite acme-client[28424]: acme-client: /var/lib/acme/accounts/letsencrypt.pem: PEM_read_PrivateKey
Dec 11 11:32:34 deposite acme-client[28424]: 140011404298968:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem/pem_lib.c:704:Expecting: ANY PRIVATE KEY
Dec 11 11:32:34 deposite acme-client[28424]: acme-client: bad exit: acctproc(28428): 1
Dec 11 11:32:34 deposite systemd[1]: acme@XXXXX.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 11:32:34 deposite systemd[1]: acme@XXXXX.service: Unit entered failed state.
Dec 11 11:32:34 deposite systemd[1]: acme@XXXXX.service: Failed with result 'exit-code'.

Sandboxing messages are gone. But something is still not working.

**Comment by repsac-by** [comment]
@cjsthompson  You have damaged private keys. You need to remove them this will allow acme-client create a new one.

Please if you have any questions that relate to my package, then ask [here](https://aur.archlinux.org/packages/acme-client-git/)  or [here](https://github.com/repsac-by/aur-acme-client-git)

**Comment by cjsthompson** [comment]
That was indeed one of the problems. But even after "rm -rf /var/lib/acme/accounts /var/lib/acme/certs" I still get "bad exit: acctproc(28428): 1".

**Comment by repsac-by** [comment]
@cjsthompson You must not remove these directories, they are a part of the package and not created automatically.
```
/var/lib/acme/accounts
/var/lib/acme/certs
```
You have to create them manually or reinstall the package.

**Comment by cjsthompson** [comment]
Thanks for the hints. It worked :)

**Comment by kristapsdz** [comment]
I'm a little lost here... are any syscalls still being flagged by seccomp?

@repsac-by, you can always disable the seccomp by commenting it out in the GNUmakefile.  But that's a bad idea: the whole problem with seccomp is that it's a moving target across versions of Linux, hardware, and (say) libc.  I'm sure that somebody using acme-client on ARM will have other system calls kill the acme-client process.  Until people run it and report problems, I won't know which need to be whitelisted.  It's a painful growing process, but sadly, that's the only way to do it on seccomp.  I don't like it either, but that's why I avoid Linux!

I'll respond to reports of system calls to whitelist as soon as possible.  If you need to reach me more quickly, send a message to me and I can get you my jabber account name.

**Comment by repsac-by** [comment]
@kristapsdz
```
The seccomp sandbox has failed, error: 4:95.
The seccomp sandbox has failed, error: 7:2.
```
I don't know whether it is necessary and what are the numbers to check
```
 2 => open
 4 => stat
 7 => poll
95 => umask
```

**Comment by kristapsdz** [comment]
Sorry everybody, I'm disabling seccomp by default.  I'll have a detailed reason why in the next release, and how to use it on a custom basis, but it will no longer be enabled, and I won't take bug reports for it.  Sorry!  (It's not you, all of you are great --- it's just that seccomp is horrible.)

**Comment by mixedCase** [comment]
@kristapsdz The problems you mentioned in seccomp appear as well on the other systems if a different libc were to be used, it's just that they are designed under the assumption that there's a single one.

I commented it on Hacker News but felt it was worth asking you directly: why not support musl only? In fact, when it comes to security software, is it not the most responsible choice to do so? Any distro that wishes to ship acme-client-portable can package musl for it (most do already, anyway).

**Comment by kristapsdz** [comment]
It's not just libc, it's hardware as well.  Can you guarantee that the same filter for x86_64 will work with ARM?  It's not even clear whether it will work between musl distributions.  Like I said, I'm happy to merge patches and be as careful as I can with them, but I won't enable it by default unless there's overwhelming consensus that it works.  (That might start with a certain subset, like musl systems with libseccomp --- who knows!)
