### ISSUE TITLE
Getting bad HTTP: 400 errors

### ISSUE THREAD

**Issue by attilagyorffy** [kristapsdz/letskencrypt-portable#14]
Hi there,

I'm trying to migrate from letsencrypt.sh to acme-client via the FreeBSD ports and getting the following error when running it:

```
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: bad HTTP: 400
```

My `acme-client.sh` that I'm using to invoke the client looks like the following (this is the base sample that comes with the port with the extra `-vv` params added):

```sh
#!/bin/sh -e

BASEDIR="/usr/local/etc/acme"
SSLDIR="/usr/local/etc/ssl/acme"
DOMAINSFILE="${BASEDIR}/domains.txt"
CHALLENGEDIR="/usr/local/etc/ssl/acme"

[ ! -d "${SSLDIR}/private" ] && mkdir -pm700 "${SSLDIR}/private"

cat "${DOMAINSFILE}" | while read domain line ; do
   CERTSDIR="${SSLDIR}/${domain}"
   [ ! -d "${CERTSDIR}" ] && mkdir -pm755 "${CERTSDIR}"
   set +e # RC=2 when time to expire > 30 days
   acme-client -b -C "${CHALLENGEDIR}" \
               -k "${SSLDIR}/private/${domain}.pem" \
               -c "${CERTSDIR}" \
               ${domain} ${line} \
               -vv
   RC=$?
   set -e
   [ $RC -ne 0 -a $RC -ne 2 ] && exit $RC
done
```

The private keys were copied from letsencrypt.sh and are placed in `/usr/local/etc/ssl/acme/private/`

Given that this looks a bit like a black box am not sure how to proceed. Any help would be much appreciated, thank you in advance.

-- Attila

**Comment by kristapsdz** [comment]
All I can see is that the **-vv** line is coming after your arguments.  Try running just that command and see if you can deduce something.  If you'd rather keep the trace off github but can't make sense of it, just e-mail me.

**Comment by attilagyorffy** [comment]
@kristapsdz That's a good catch. I am now making progress however am stuck a bit. My webserver is nginx and is running as www on FreeBSD:

```
# procstat -s 2850
  PID COMM              EUID  RUID SVUID  EGID  RGID SVGID UMASK FLAGS GROUPS         
 2850 nginx               80    80    80    80    80    80   000 -     80
# id www
uid=80(www) gid=80(www) groups=80(www)
```

However when I am running `acme-client.sh` it is creating challenge files with permissions 
`-r--r-----  1 root  wheel` that are needless to say aren't readable by nginx and the challenge fails with a HTTP 403.

What is the proposed way to issue this? According to the `acme-challenge` man page this may be a known issue?

```
BUGS
     The challenge and certificate processes currently retain their (root)
     privileges.
```

**Comment by attilagyorffy** [comment]
@Sp1l given that you are the maintainer of the port I wonder if you have an idea?

**Comment by kristapsdz** [comment]
What's your umask?

**Comment by attilagyorffy** [comment]
You are right, it was `0027` and so the world read permission was revoked. By running `.acme-client.sh` with an explicit `0022` I'm getting the right permissions again:

`-r--r--r--`

Thank you.

**Comment by kristapsdz** [comment]
I now use umask(2) for the challenge-file creation, so your umask will not affect that.  Thanks!
