### ISSUE TITLE
Error 4:95 with libseccomp

### ISSUE THREAD

**Issue by skarnet** [kristapsdz/letskencrypt-portable#16]
Hello,

I can't make acme-client-portable work with libseccomp, whereas it works flawlessly without it.
Kernel: Linux-3.18.43. I have no choice about the kernel, unfortunately; if the answer is "it's too old", I'll understand. But it has CONFIG_SECCOMP=y, as well as CONFIG_SECCOMP_FILTER=y and CONFIG_HAVE_ARCH_SECCOMP_FILTER=y.
Libc: musl. The system has been entirely hand-built from scratch.
The numbers reported by the error message are 4:95. 

 Please let me know if you need more information.

**Comment by kristapsdz** [comment]
I'm disabling seccomp by default.  (More information why when I do the next release.)  Please try again and let me know if you have issues!

**Comment by skarnet** [comment]
Well I've already disabled seccomp in my build, since I needed to make acme-client work one way or another. Thanks for the reply, and I'll read the release notes with curiosity. :-)
