### ISSUE TITLE
dependent on libbsd, but libbsd dependent on OpenSSL

### ISSUE THREAD

**Issue by m0yellow** [kristapsdz/letskencrypt-portable#17]
tried compiling from git,
installed libbsd from src.rpm, needed openssl-devel to compile, when trying to get libreSSL into the system, my knowledge (or time) so far fails, since the base install of my linux is dependent on OpenSSL.

Is there an easy way to get acme-client-portable compiled against a local LibreSSL? 
(Do I need more GNUMakefile-Foo for that?)

**Comment by kristapsdz** [comment]
Yes.  Install libressl into /opt or wherever won't clobber your system.  Have it be picked up by pkg-config, which should be picked up by the GNUmakefile.  But there's probably somebody who's working on libressl for your distribution, so you may want to contact them to ask questions.  This isn't an acme-client issue, so I'm going to close this out.  Sorry I couldn't help more.
