### ISSUE TITLE
dns-01 possible?

### ISSUE THREAD

**Issue by m0yellow** [kristapsdz/letskencrypt-portable#20]
I'm generating letsencrypt certificates for internal domains currently with a public dns challenge to avoid opening up internal hosts to the internet with a shell script.
(my longtime goal is to replace all the self signed in house certs with LE ones.)

To make my setup future proof (a.k.a. secure), I'm thinking about your client.
Are you in the progress of writing it? Or is there any clue how a contributor could hack together the dns challenge support?

**Comment by kristapsdz** [comment]
See the **-t** flag.  You can interact directly with the challenge that way.  (The "Challenges" section explains the protocol.)

**Comment by m0yellow** [comment]
Thanks for the link, had the man page open while writing the issue, but must have missed it.
(D'oh). 
Your hint is highly appreciated
