### ISSUE TITLE
[FEATURE REQUEST] Ubuntu PPA (please assign it for me)

### ISSUE THREAD

**Issue by silvioprog** [kristapsdz/letskencrypt-portable#24]
Hello,

On Ubuntu, it would be nice to install acme-client with apt:

```bash
sudo apt install acme-client-portable
```

I have some knowledge about building PPAs and I would be glad if you allow me to that. :-)

**Comment by kristapsdz** [comment]
There are lots of downstream versions of acme-client.  If you're taking on maintainership for a downstream port or package (or whatever it's called for Ubuntu) then let me know if you have any portability issues and I'll look into them!

**Comment by silvioprog** [comment]
OK dude thanks! :-)
