### ISSUE TITLE
[FEATURE REQUEST] autotools integration

### ISSUE THREAD

**Issue by silvioprog** [kristapsdz/letskencrypt-portable#25]
Hello,

What do you think about to build and install acme-client as below?:

```bash
./configure
make
sudo make install
```
If you like this we could create the autotools files. :-)

**Comment by dasJ** [comment]
Why would anyone want that? What are the upsides?

**Comment by silvioprog** [comment]
Well, autotools helps to avoid building shell by hands:

https://github.com/kristapsdz/acme-client-portable/blob/master/GNUmakefile#L25

and it is the default build system of many popular libraries (like libressl, libbsd etc).

**Comment by kristapsdz** [comment]
I wouldn't use autoconf, but I have thought of using a configuration script just to clean up the GNUmakefile.  But as there have been very few complaints about portability, it's just overkill for now.

Note that the only shell work in the GNUmakefile for the portable version is for my own use, keeping -portable in sync with the main repository.
