### ISSUE TITLE
[FEATURE REQUES] acme-client-portable as library (libacp?)

### ISSUE THREAD

**Issue by silvioprog** [kristapsdz/letskencrypt-portable#26]
Hello,

I've studied acme-client-portable sources and noticed that it could be a very useful library to be used in other languages like Python, JS, Pascal etc.

So, what do you think about to refactore acme-client-portable in a near future to make it a library? :-) With the library in hands, the acme-client-portable tool could use it. The curl tool follows a similar approach, it uses its libcurl library, and the new features are implemented in the library.

**Comment by kristapsdz** [comment]
It's pretty straightforward to library-ise (see main.c), but I don't have a use case for that, so it's unlikely to happen without somebody else doing so. ;)

**Comment by silvioprog** [comment]
Indeed. I totally agree!
