### ISSUE TITLE
[FEATURE REQUEST] cron entry

### ISSUE THREAD

**Issue by silvioprog** [kristapsdz/letskencrypt-portable#27]
Hello,

It would be nice to use something like this:

```bash
# acme-client -d 60
```

`-d` - it creates a cron entry for 60 days.

Please sorry for a lot of FEATURE REQUEST, but I'm just want to improve this awesome tool (and I think I'm able to help in the implementation :-) ).

**Comment by kristapsdz** [comment]
This is already given as part of an example in the manpage.  Take a look at the EXAMPLES and see if that part makes sense.  Having it actually modify the crontab is beyond the scope of the application.  But thanks!
