### ISSUE TITLE
letskencrypt: /var/empty: chroot: No such file or directory

### ISSUE THREAD

**Issue by tfarina** [kristapsdz/letskencrypt-portable#3]
Now I'm getting the following:

$ sudo LD_LIBRARY_PATH=/usr/local/lib ./letskencrypt -vNn foo.com www.foo.com

: letskencrypt: /var/empty: chroot: No such file or directory
/var/empty: chroot: No such file or directory
/var/empty: chroot: No such file or directory
letskencrypt: /var/empty: chroot: No such file or directory
/var/empty: chroot: No such file or directory

I'm on Ubuntu.

**Comment by kristapsdz** [comment]
Ubuntu doesn't have /var/empty?  What does it use instead for privilege-dropped daemons?

**Comment by kristapsdz** [comment]
You can always just mkdir /var/empty as root in the meantime.

**Comment by tfarina** [comment]
Did that, now it is the following:

$ sudo LD_LIBRARY_PATH=/usr/local/lib ./letskencrypt-portable/letskencrypt -vNn foo.com www.foo.com
letskencrypt: -k file must not exist when using -N
letskencrypt: -f file must not exist when using -n

**Comment by kristapsdz** [comment]
It's pretty self-explanatory.  You used -N when the domain key already exists and -n when the account key already exists.  The default locations are privkey.pem in /etc/ssl/letsencrypt/private for the former and /etc/letsencrypt for the latter.  If you already made them, drop the -N and -n.

**Comment by tfarina** [comment]
Now with just -v it is the following:

$ sudo LD_LIBRARY_PATH=/usr/local/lib ./letskencrypt-portable/letskencrypt -v 
letskencrypt: letskencrypt: /etc/letsencrypt/privkey.pem: PEM_read_PrivateKey
139701815826080:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY
/etc/ssl/letsencrypt/private/privkey.pem: PEM_read_PrivateKey
139701815826080:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY
letskencrypt: bad exit code: keyproc(9240)
letskencrypt: bad exit code: acctproc(9241)

**Comment by kristapsdz** [comment]
@tfarina, I really can't help you with so little information.  Please clear all the directories the system has used (the manpage will tell you what they are), read the manpage, and re-run the program.  If you can demonstrate that your keys are valid and letskencrypt isn't able to read them, then that's a problem.  Obviously the keys in the given locations aren't really private keys: you've either put something else there or the files are empty or something.  I'm closing this issue until you have a bug to report.

**Comment by tfarina** [comment]
$ sudo rm -rf /etc/ssl/letsencrypt
$ sudo rm -rf /etc/letsencrypt
$ sudo rm -rf /var/www/letsencrypt
$ sudo rm -rf /var/empty
$ sudo mkdir /var/www/letsencrypt
$ sudo mkdir /etc/ssl/letsencrypt
$ sudo mkdir /etc/ssl/letsencrypt/private /etc/letsencrypt
$ sudo chmod 0700 /etc/ssl/letsencrypt/private /etc/letsencrypt
$ sudo mkdir /var/empty
$ sudo LD_LIBRARY_PATH=/usr/local/lib ./letskencrypt-portable/letskencrypt -vNn foo.com www.foo.com
letskencrypt: /etc/ssl/letsencrypt/private/privkey.pem: generated RSA domain key
letskencrypt: /etc/letsencrypt/privkey.pem: generated RSA account key
letskencrypt: https://acme-v01.api.letsencrypt.org/directory: directories
letskencrypt: acme-v01.api.letsencrypt.org: DNS: 2.19.132.37
letskencrypt: tls_init: No such file or directory
letskencrypt: https://acme-v01.api.letsencrypt.org/directory: bad comm
letskencrypt: bad exit: netproc(10461): 1

What more information do you need to make it work out of the box than the command lines I'm running?

**Comment by kristapsdz** [comment]
Ok, much better.  It looks like tls_init() can't be run within a chroot.  (It calls through to tls_config_new(), which requires /etc/ssl/cert.pem.)  I'll put up a fix in a few.

**Comment by kristapsdz** [comment]
Actually, that doesn't seem to be it.  What version of libressl are you running?  Can you run ldd on the letskencrypt binary?

**Comment by tfarina** [comment]
$ dpkg -l | grep ssl
ii  libgnutls-openssl27:amd64            2.12.23-12ubuntu2.5              amd64        GNU TLS library - OpenSSL wrapper
rc  libpolarssl5                         1.3.4-1                          amd64        lightweight crypto and SSL/TLS library
ii  libssl-dev:amd64                     1.0.1f-1ubuntu2.19               amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.0.0:amd64                    1.0.1f-1ubuntu2.19               amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                              1.0.1f-1ubuntu2.19               amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                       0.13-2ubuntu6                    amd64        Python 2 wrapper around the OpenSSL library
ii  ssl-cert                             1.0.33                           all          simple debconf wrapper for OpenSSL

 $ ldd ./letskencrypt
        linux-vdso.so.1 =>  (0x00007fff79192000)
        libtls.so.11 => /lib/x86_64-linux-gnu/libtls.so.11 (0x00007ff50f6bc000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007ff50f45d000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007ff50f080000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ff50ee71000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff50eaac000)
        libssl.so.39 => /lib/x86_64-linux-gnu/libssl.so.39 (0x00007ff50e84b000)
        libcrypto.so.38 => /lib/x86_64-linux-gnu/libcrypto.so.38 (0x00007ff50e442000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff50e23e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff50f8d0000)

**Comment by kristapsdz** [comment]
Do you have libressl installed?  (Note, lib_re_ssl, as in [here](http://www.libressl.org/).)

**Comment by kristapsdz** [comment]
As this will be up to a downstream packager (creating /var directories isn't right for third-party software to do!), I'm closing this out.  I have added a value to config.h, `PATH_VAR_EMPTY`, which can be set to any directory by downstream.
