### ISSUE TITLE
Agreement url needs to be upgraded

### ISSUE THREAD

**Issue by angelloGit** [kristapsdz/letskencrypt-portable#47]
root@lepton ~/bin # ./update_ssl.sh
acme-client: /etc/ssl/acme/xxxxxxxxxxxxxxxx: creating directory
acme-client: /etc/ssl/acme/private/xxxxxxxxxxxxxxxxx: creating directory
acme-client: /etc/acme/xxxxxxxxxxxxxxxxxxx: creating directory
acme-client: /etc/acme/xxxxxxxxxxxxxxx/privkey.pem: generating RSA account key
acme-client: /etc/ssl/acme/private/xxxxxxxxxxxxxx/privkey.pem: generating RSA domain key
acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:78:19d::3d5
acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:78:189::3d5
acme-client: acme-v01.api.letsencrypt.org: DNS: 95.101.240.249
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: new-reg
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: bad HTTP: 400
acme-client: transfer buffer: [{ "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]", "status": 400 }] (267 bytes)
acme-client: bad exit: netproc(29347): 1

it seems to Letsencrypt changes their agreement every year

**Comment by cpu** [comment]
Hi @angelloGit,

I believe this is a duplicate of https://github.com/kristapsdz/acme-client-portable/issues/46

**Comment by angelloGit** [comment]
absolutly
